local Tunnel = require("resources/vrp/lib/Tunnel")
local Proxy = require("resources/vrp/lib/Proxy")
vRP = Proxy.getInterface("vRP")
vRPserver = Tunnel.getInterface("vRP")

RegisterClientEvent('frfuel:paidfuel')
AddEventHandler('frfuel:paidfuel', function(cost)
	vRP.notify("You have paid $" .. cost .. " for fuel")
end)

RegisterClientEvent('frfuel:stealfuel')
AddEventHandler('frfuel:stealfuel', function(cost)
	vRP.notify("You have driven off without paying $" .. cost .. " for fuel")
	vRP.notify("Police may have been notified!")
end)