client_script "cl_voip.lua"
server_script "sv_voip.lua"
client_script "client.lua"
client_script "client2.lua"
client_script "lock_client.lua"
client_script "lock_server.lua"
client_script "handsup_client.lua"